### ISSUE TITLE
Objects are fully traversed

### ISSUE THREAD

**Issue by Americas** [shouldjs/format#6]
As it stands, when an object is formatted, it is fully traversed. This causes OOM errors when we have very large objects to test.

Also, as mentioned in this issue shouldjs/should.js##108, some objects are too big for a print to be useful, and a behavior of max depth would be very useful.

Furthermore, as of node v7, the behavior of `captureStackTrace` has changed, it no longer lazy loads the stacktrace. This means that the formatter is always called when an AssertionError is reached, even in the case of a negated chain.

**Comment by Americas** [comment]
PR #5 fixes this by setting a default limit depth to all object formatting.

**Comment by btd** [comment]
I will take a look on all this. Do you have any url where i can read about `captureStackTrace` change?

**Comment by Americas** [comment]
Saw it mentioned [here](https://bugs.chromium.org/p/v8/issues/detail?id=5293), but found little more.

**Comment by btd** [comment]
Well, thanks for contribution, but my thoughts:
1. It really does not fix this issue. It is workaround, and also not implemented correctly. It is implemented not correctly because you set depth only for object instances (you can get previous result when you use other objects (user defined classes, Maps etc)).
We should not set default depth to 4 because it is breaking change. It should be opt-in not opt-out.
Also when you set depth on format, it will format everything, but usually user wants to make specific format for one exactly object (or object type). So i believe we need to think in this direction (maybe more simple adding formatting, or some easy way to set format for specific part of assertion).
2. captureStackTrace change also not fixed by this. As it stands in pointed issue, it makes more sense to fix AssertionError inheritance.

So all this going, i will not merge this, but will first try to look at perfomance of should.js in v7. After this it maybe will wake sense to fix item 2.

**Comment by btd** [comment]
I just tried to run tests (we have [one for perfomance](https://github.com/shouldjs/should.js/blob/master/test/perf.test.js) and i did not notice any significant change (whole suite executed for 2s 39ms). So i am closing this.
Please feel free to open issues (but in should.js repo) about perfomance issues, i understand exist different cases, and i could not notice some of them. 
I am closing this and related PR.

**Comment by Americas** [comment]
This is the quickest way without any breaking changes that I saw of patching the changes put forth by node v7. I can change the value to be opt-in. As for the traversal not being generic, I can also find a way to change that.

I can turn this into a non-breaking change. WDYT?

Also, i was running your performance test (only the perf.test.js), running it in node v7 has a considerable loss of performance (in v6.9.0 takes < 10ms, in node v7.0.0 it takes around 730ms). Is a 7000% increase in time not significant?

**Comment by btd** [comment]
I am OK to merge something like this with changes I mentioned. but you
should understand it is not a fix for issue at all.
I am working on fixing this in AssertionError.

Also about what I mean with significant. when 1 artificial test changed
from 10 ms to 700 ms it is not significant IMO.  if you tell me your app
tests executed after upgrading to v7 longer to period, yes it is
significant. This change in v8 only affecting when your actual test failed.
also for negated cases but in my experience number of such tests usually
very low.

5 Дек 2016 г. 14:53 пользователь "Paulo R Lopes" <notifications@github.com>
написал:
